#!/usr/bin/env php

<?php

require __DIR__.'/vendor/autoload.php';

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__ );
$dotenv->load();

use Symfony\Component\Console\Application;
use App\Commands\GenerateUser;

$application = new Application();

// ... register commands
$application->add(new GenerateUser());

$application->run();
